switch to gh pages

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -17,7 +17,12 @@ jobs:
       - uses: actions/checkout@v3
       - uses: actions/setup-node@v3
         with:
-          node-version: '19'
+          node-version: '20'
+      - name: validate branch
+        if: ${{ inputs.build_branch == 'main' }}
+        run: |
+          echo 'cannot target main branch' \
+          && exit 1
       - name: prepare env
         run: echo "${{ secrets.DOT_ENV }}" >> $GITHUB_ENV
       - name: install deps
@@ -36,6 +41,6 @@ jobs:
           && git config user.name 'github-actions' \
           && git config user.email 'actions@github.com' \
           && git commit -m 'build' \
-          && git push -f -u origin ${{ inputs.build_branch }}
-  
-        
+          && git subtree split --prefix build -b tmp \
+          && git push -f -u origin tmp:${{ inputs.build_branch }}
+ 
